# Generated by Django 4.0.5 on 2022-06-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_formattention_created_at_formlearning_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lgpdpermissions',
            name='bio_permission',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lgpdpermissions',
            name='email_permission',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lgpdpermissions',
            name='name_permission',
            field=models.BooleanField(default=True),
        ),
    ]
