# Generated by Django 4.0.5 on 2022-06-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_lgpdpermissions_bio_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lgpdpermissions',
            name='bio_permission',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='lgpdpermissions',
            name='email_permission',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='lgpdpermissions',
            name='name_permission',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
