# Generated by Django 4.0.5 on 2022-06-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_lgpdpermissions_bio_permission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lgpdpermissions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
